environment: 1
log_level: 6
address: :3000
frontend_url: http://localhost:3000
cors:
  - http://localhost:8080
mysql_dsn: dev1:20221126@tcp(localhost:3306)/dev1?charset=utf8mb4&parseTime=True&loc=Local
mysql_migrate: true
smtp_host: smtp.example.com:587
smtp_mail: noreply@example.com
smtp_user: noreply@example.com
smtp_pass: 12345678
ldap_address: localhost:636
ldap_base_dn: dc=com
ldap_cert: |
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
jwt_secret: 1234567890